# Generated by Django 3.0.2 on 2020-01-25 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50, verbose_name='Codigo')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('product_val_min', models.FloatField(default=0, verbose_name='Precio Minimo')),
                ('product_val_med', models.FloatField(default=0, verbose_name='Precio Promedio')),
                ('product_val_max', models.FloatField(default=0, verbose_name='Precio Maximo')),
                ('product_val_ult', models.FloatField(default=0, verbose_name='Precio Ultimo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
