# Generated by Django 3.0.2 on 2020-01-25 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_auto_20200125_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_cant', models.FloatField(default=0, verbose_name='Cantidad')),
                ('stock_vence', models.DateTimeField(verbose_name='Fecha de Vencimiento')),
                ('stock_serie', models.CharField(max_length=255, verbose_name='Numero de Lote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Productos')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
    ]
